LOAD DATA INFILE 'Item.dat' INTO TABLE Item FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA INFILE 'User.dat' INTO TABLE User FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA INFILE 'ItemBid.dat' INTO TABLE ItemBid FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA INFILE 'ItemCategory.dat' INTO TABLE ItemCategory FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
